// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElPagination: typeof import('element-plus/es')['ElPagination']
        ElSwitch: typeof import('element-plus/es')['ElSwitch']
        HelloWorld: typeof import('./components/HelloWorld.vue')['default']
        Icons: typeof import('./components/Icons.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}

export {}
